# Yoga Studio (name, location, phone_number, website)
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))
YogaStudio.create(name: Faker::Name.name, location: Faker::Address.full_address, phone_number: Faker::Base.numerify('+90(###) ### ###'), website: Faker::Internet.url(host: 'example.com'))

# Users(name, age, number, years_experience)
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))
User.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), years_experience: Faker::Number.number(digits: 2))

# Yoga Reviews(user_id,yoga_studio_id, rating)
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
Review.create(user_id: User.all.sample.id, yoga_studio_id: YogaStudio.all.sample.id, rating: Faker::Number.between(from: 1, to: 5))
